#!/bin/bash
echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
docker tag "markusressel/grocy-telegram-bot" "markusressel/grocy-telegram-bot:${TRAVIS_TAG}"
docker push "markusressel/grocy-telegram-bot:${TRAVIS_TAG}"